[build]
  publish = "public"
  command = "chmod 755 task_resume_get.sh task_site_build.sh && ./task_site_build.sh"

[build.environment]
  HUGO_VERSION = "0.122.0"
  NODE_VERSION = "18"

[build.processing.images]
  compress = true
